### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by dimqua** [chenxiaolong/DualBootPatcher#724] opened 2017-08-23 03:59 UTC
Please consider to include the app into [F-Droid](https://f-droid.org/).

FYI: https://gitlab.com/fdroid/rfp/issues/295

**Comment by webmaster33** [comment] 2017-08-23 11:25
Good idea.

**Comment by thermatk** [comment] 2018-05-30 07:32
@chenxiaolong please confirm you wouldn't oppose this, so that someone else can actually do that :+1:

**Comment by IzzySoft** [comment] 2019-01-29 14:19
@chenxiaolong @webmaster33 *ping* any response? Can we count the "Good idea" as a "Go"?

**Comment by klorinczi** [comment] 2019-01-29 14:26
I think it can be included into F-Droid, if the F-Droid does not prohibit such kind of app.

**Comment by IzzySoft** [comment] 2019-01-30 10:05
@klorinczi "such kind of app" is not the issue. The issue is [prebuilt binaries](https://gitlab.com/fdroid/rfp/issues/295#note_136279822) being used. F-Droid only builds from source, the entire app. So "blobs" are not permitted.

**Comment by chenxiaolong** [comment] 2019-01-30 13:07
The build scripts for all the prebuilt libraries are provided here: https://github.com/chenxiaolong/DualBootPatcher/tree/master/thirdparty and can be built with:

```
cd third_party/the_library
../makepkg -fcC CARCH=armv7 --sign
../makepkg -fcC CARCH=aarch64 --sign
../makepkg -fcC CARCH=x86 --sign
../makepkg -fcC CARCH=x86_64 --sign
```

The eventual goal is to stop relying on prebuilt things and have CMake compile them when building DBP, but I don't expect that to be done any time soon, unfortunately. Quite a few of the libraries aren't built with CMake so those build scripts would have to be converted to CMake.

**Comment by IzzySoft** [comment] 2019-01-30 14:24
@chenxiaolong Thanks! Transferred that information over to our tracker and asked one of our "builders" to have a look.

**Comment by chenxiaolong** [comment] 2019-04-01 02:05
Quoting my post over at GitLab: https://gitlab.com/fdroid/rfp/issues/295#note_155875325

> Not sure if anyone is still working on this, but I wouldn't recommend working on this any further. The next major version of DBP will no longer have an Android app because all of the features will be available via a graphical UI when booted to the device's recovery mode.

**Closed by chenxiaolong** 2019-04-01 02:05 UTC

**Comment by klorinczi** [comment] 2019-04-01 05:00
@chenxiaolong: I welcome the planned DBP new recovery features, this is something I wait since a long time. 

However I like to have an Android app to list, edit, control installed OSes on the phone. 
I would miss the in-app flash feature of DBP.
Also I would miss the screenshot ability, which is an OS feature, can not do from recovery.

So while I welcome new recovery features, I would recommend to keep DBP Android app.
