### ISSUE TITLE
Having trouble with CM12.1 installation

### ISSUE THREAD

**Issue by Caio99BR** [chenxiaolong/DualBootPatcher#58] opened 2016-01-27 02:40 UTC
The installation go fast and i not unpack the system files.
Maybe because new LP/MM installation method.
I updated TWRP (branch 5.1) to new blockimg (version 3) since CM recovery use this, and force us to edit system.tranfer.list.
But backing to error, the files not is extracted but boo.img is flashed.
Here core of error:
``
using existing stash /cache/recovery/90366e4fa7117d6830dd04f8b09a7469550bb932/
``
``
not a block device; skipping erase
``
``
failed to execute command [erase 2,0,233984]
``
I tested the zip before and work.
Note: i can't patch files and update ramdisk in new versiin, i not tested with previous of this.

**Comment by chenxiaolong** [comment] 2016-01-27 06:20
> I updated TWRP (branch 5.1) to new blockimg (version 3) since CM recovery use this, and force us to edit system.tranfer.list.

Do you have a link to the source code for this?

---

During the `not a block device; skipping erase` step, the function actually returns a failure code (`-1`), so I'm guessing that why it fails. Maybe update-binary didn't check the return values before?

---

> Note: i can't patch files and update ramdisk in new versiin, i not tested with previous of this.

That's very strange. Can you grab a logcat?

**Comment by Caio99BR** [comment] 2016-01-27 09:41
> Do you have a link to the source code for this?

Yes, here the Source: https://github.com/TeamVee/android_bootable_recovery/tree/android-5.1

---

 > Maybe update-binary didn't check the return values before?

Maybe, since same thing happened in recovery. Here the MultiBoot.log: [MultiBoot.log.txt](https://github.com/chenxiaolong/DualBootPatcher/files/106323/MultiBoot.log.txt)

---

> Can you grab a logcat?

First logcat: Error in line 696, i cant go fast to ROM section, if i go fast the app crash (I have this error since firsts tests, no way to add a Loading Page, like Kernel Adiutor) - [logcat.txt](https://github.com/chenxiaolong/DualBootPatcher/files/106335/logcat.txt)

Second logcat: Same error of previous log? Error in line 739, i went to App Sharing and after error message (if not have updated ramdisk ...), i go directly to Update Ramdisk (changed ROM first because low resolution) - [logcat2.txt](https://github.com/chenxiaolong/DualBootPatcher/files/106341/logcat2.txt)

Third logcat: I tried to patch same zip, same error? Error in line 737, no workaround, i went straight - [logcat3.txt](https://github.com/chenxiaolong/DualBootPatcher/files/106346/logcat3.txt)

Last logcat: No comments (note i have choose the wrong file first and last the correct, due to my stupidity) - [logcat4.txt](https://github.com/chenxiaolong/DualBootPatcher/files/106350/logcat4.txt)

**Comment by chenxiaolong** [comment] 2016-01-27 16:59
Thanks for all the logs! I'll take a look at them after work.

The logcats look really bad. I haven't seen a crash like that for a very long time. Are you using a custom build or one from https://snapshots.noobdev.io/? If you're using a custom one, could you try deleting the build directory and rebuilding again?

Btw, is this the zip you were trying to patch? https://www.androidfilehost.com/?fid=24389512218018529

**Comment by Caio99BR** [comment] 2016-01-27 17:06
Latest snapshotn and yes

**Comment by Caio99BR** [comment] 2016-01-27 21:30
Maybe if have a way to fake a block device for cache, to blockimg stay happy and not make problems :).

And in my edited TWRP this line not is present https://github.com/CyanogenMod/android_bootable_recovery/blob/cm-12.1/updater/blockimg.c#L1435

I will test one thing and after i report if sucess.

**Comment by chenxiaolong** [comment] 2016-01-27 21:55
@Caio99BR Yeah, a loop device would be a great idea, though I'll need to do some testing to see if it supports `BLKDISCARD` that the updater is trying to do.

Any chance you could send me a copy of the update-binary that had issues? I'd rather not download the source code for the whole ROM to build it :)

**Comment by chenxiaolong** [comment] 2016-01-27 21:58
Damn it, I broke my streak of having absolutely zero memory errors in my C and C++ code :D I was able to reproduce the crashes. They're caused by the code for parsing the `boot.img`. I'll report back with more details once I figure out what's going on.

**Comment by Caio99BR** [comment] 2016-01-28 16:24
Sorry for not reply before i was without power yesterday, here the update-binary (mtp://[usb:001,005]/Cart%C3%A3o%20SD/update-binary just remove .txt :P).

And now i can update ramdisk and patch files (but i still cant go fast to ROMs Section :P), and no, the LGs MSM7x27a not have support to by-name directory, if had it all would be easier.

//Note: I still cant install the CM12.1, same issue.

**Comment by chenxiaolong** [comment] 2016-01-30 01:23
@Caio99BR Thanks for the link to the update-binary! I'll do some testing with it.

I started looking into the using a loop device yesterday and it seems like the kernel will simply ignore `BLKDISCARD` and return a success code (!). That is great because the current mbtool code doesn't actually erase anything, so no functionality is lost.

**Comment by Caio99BR** [comment] 2016-01-30 01:46
This is good, i wait for update :).
Note: I can't go fast to ROMs section fast (in CM11 and CM12.1[i installed pure, like a primary ROM, copied the system to cache, restore my old ROM, install patched cm12.1 zip and copied to null folder and rebooted, inutility but is my experience, in this time i fixed 4 bugs in this ROM :)]).

**Comment by chenxiaolong** [comment] 2016-01-30 02:13
@Caio99BR Do you mean the ROMs section crashes or some other error happens? Could you grab a logcat? :)

**Comment by chenxiaolong** [comment] 2016-01-30 07:07
@Caio99BR Can you try the `mbtool-loop-dev` branch and see if it fixes the installation issues? I was able to successfully flash a ROM after replacing its update-binary with yours :)

Should be fixed by commit: 54237f00538739a89e9e63e5d5ca37f094351bec

**Comment by Caio99BR** [comment] 2016-01-31 02:17
> @Caio99BR Do you mean the ROMs section crashes or some other error happens? Could you grab a logcat? :)

https://gist.github.com/Caio99BR/ce805a7066a69bb0a410

I get a lot of time to build, since i deleted old sdk/ndk/android-studio.
Testing it now.

**Comment by Caio99BR** [comment] 2016-01-31 03:32
The installation get a lot of time, i wait 10m but nothing, after i tried in recovery but get a lot of time before start real updater-binary.
I will lose more time trying to install.
Logcat not say nothing useful, maybe it is so patience :P

**Comment by chenxiaolong** [comment] 2016-01-31 04:34
> https://gist.github.com/Caio99BR/ce805a7066a69bb0a410
> 
> I get a lot of time to build, since i deleted old sdk/ndk/android-studio.
> Testing it now.

Thanks! Looks like there might possibly be another bug in the boot.img code. Can you send me all of the boot.img files in `/sdcard/MultiBoot`? (assuming you have a fast connection, unlike my 1Mbps upload :P)

**Comment by chenxiaolong** [comment] 2016-01-31 04:37
> The installation get a lot of time, i wait 10m but nothing, after i tried in recovery but get a lot of time before start real updater-binary.
> I will lose more time trying to install.
> Logcat not say nothing useful, maybe it is so patience :P

When you flash in recovery and it hangs, `adb pull /tmp/recovery.log` might get some useful logs. I'll do some testing on another one of my devices to see if I find any other issues. :)

**Comment by Caio99BR** [comment] 2016-01-31 22:40
[MultiBoot.log.txt](https://github.com/chenxiaolong/DualBootPatcher/files/111553/MultiBoot.log.txt)

I not will upload this, ever my poor net don't help.
No log from recovery, for now.
And log is from latest build with old installation, i will try to install from recovery without old installation.

**Comment by Caio99BR** [comment] 2016-02-08 01:56
You can merge this, but because some devices not support blkdiscard very good (like mine), so just works.
For now is best put a message like "Due to LP/MM System Image Flash, this will get little bit 'more' time", just in case, since many peoples not like to wait 15m or more for install a ROM.

**Comment by chenxiaolong** [comment] 2016-02-08 08:38
@Caio99BR Thanks for the info! Will merge tomorrow. One thing to note: from your previous post, the log contained:

```
[V] Copying system to temporary image
[E] There is not enough space to create /raw/data/.system.img.tmp
[E] - Needed:    973078528 bytes
[E] - Available: 949276672 bytes
[V] 
[V] There is not enough space to create /raw/data/.system.img.tmp
[V] - Needed:    973078528 bytes
[V] - Available: 949276672 bytes
[V] Failed to create temporary image /raw/data/.system.img.tmp
[V] Trying to create temporary image on external SD
[V] (This will be slow)
[D] /raw/extsd/.system.img.tmp: Creating new 973078528 ext4 image
[D] Running command: [ make_ext4fs, -l, 973078528, /raw/extsd/.system.img.tmp ]
```

Does that still happen? If so, then the installation is slow because a temporary image is being created on the SD card (which happens because you're out of space on `/data`). Freeing up some space should make the installation go much faster.

**Comment by Caio99BR** [comment] 2016-02-08 13:56
I made this after(see size), but in two situation this is slow, obviously with image on external SD this is much more slow.

**Comment by Caio99BR** [comment] 2016-02-09 16:39
One thing, why patcher copy system to tmp image or the message is only "in case".

Other thing, that error of go fast to ROMs section only happen when no "special" action is on, like update kernel or ramdisk (i will check it again)

**Comment by chenxiaolong** [comment] 2016-02-09 16:51
The patcher will copy system to a temporary image if the zip contains a system image (eg. any AOSP ROM with `system.new.dat`). Otherwise, they will not be able to backup the Gapps or any other file specified in `/system/addon.d/`.

The temporary image is also always used when flashing any patched file for the primary ROM because there's no other safe way to prevent the zips from deleting `/system/multiboot`.

**Comment by Caio99BR** [comment] 2016-02-09 17:07
Ok.
Last things, the Zip Patching Section are using old loading (i mean JB/KK loading icon), and about need more space because the credits (i cant put the image because stock CM11 browsee not support upload images, snd I'm out of home now)

**Closed** 2016-02-16 00:49 UTC
Labels: component/libmbp, component/mbtool, kind/bug

**Comment by Caio99BR** [comment] 2016-02-16 00:50
Main issue fixed on commit https://github.com/chenxiaolong/DualBootPatcher/commit/54237f00538739a89e9e63e5d5ca37f094351bec
