### ISSUE TITLE
Dual boot utilities wrong device

### ISSUE THREAD

**Issue by wajdidhc** [chenxiaolong/DualBootPatcher#49] opened 2016-01-17 11:12 UTC
When I flash utilities in recovery it thinks my device is klte when it is k3g

**Comment by chenxiaolong** [comment] 2016-01-22 01:37
Could you post a link to the recovery image you're using? The utilities zip doesn't do any device detection. It simply uses what the recovery reports as the device.

**Comment by hankching** [comment] 2016-09-18 20:24
Confirmed that recovery is wrongly showed because of ro.product.device.

@chenxiaolong
Pls close it.

**Closed** 2016-09-20 00:52 UTC
