### ISSUE TITLE
Patching zip file

### ISSUE THREAD

**Issue by TugaPowerROM** [chenxiaolong/DualBootPatcher#29] opened 2016-01-08 17:50 UTC
It gives error 13 and wont patch zip file. OnePlus Bacon CM13.0 Android 6.0.1
Any workround?
Also see that device its supported but could not find specific thread for this device.

**Comment by Caio99BR** [comment] 2016-01-08 18:03
Try to use Win32 version to patch :D
And the error is status 16?

**Comment by TugaPowerROM** [comment] 2016-01-08 18:58
Status 13

![2016-01-08 18 56 27](https://cloud.githubusercontent.com/assets/9769460/12206607/2a239b1e-b642-11e5-923f-2eb286835082.png)

**Comment by Caio99BR** [comment] 2016-01-08 19:21
You will patch from Windows, pass to device and flash via ROMs :D 
Try r2037, and BR?

**Comment by TugaPowerROM** [comment] 2016-01-08 19:33
Read my last post, from windows it gives error also.

**Comment by TugaPowerROM** [comment] 2016-01-08 19:37
OK , with r2037 it works, but it needs a PC to do the job, not quite a nice solution.

**Comment by chenxiaolong** [comment] 2016-01-08 20:00
The error messages suck, I know :( (issue #18) Could you post the contents of `/sdcard/MultiBoot/patch-file.log`? Also, could you post a link to the file you're patching?

13 is `ErrorCode::ArchiveReadDataError`
16 is `ErrorCode::ArchiveWriteDataError`

I've never seen those occur aside from a bad download. On Android, at least, it's usually a permissions issue (`ArchiveReadOpenError` / 12 or `ArchiveWriteOpenError` / 15).

**Comment by chenxiaolong** [comment] 2016-01-08 20:03
> Also see that device its supported but could not find specific thread for this device.

Btw, I prefer tracking issues here instead of at XDA because it makes it easy to see who encountered what problems. My memory is not that great ;)

**Comment by TugaPowerROM** [comment] 2016-01-08 22:12
Here you have the ROM in question:
https://de1.androidfilehost.com/dl/9rnsH8WXzPGeANgHHXOyyw/1452437687/24352994023708117/TugaPowerM22.zip

Also see attached patch-file.log ( renamed to .txt to upload here )
[patch-file.txt](https://github.com/chenxiaolong/DualBootPatcher/files/83333/patch-file.txt)

**Comment by Caio99BR** [comment] 2016-01-08 22:19
1-08 22:49:49.819 12908 12935 E RomConfig: Failed to load /storage/emulated/0/MultiBoot/primary/config.json
01-08 22:49:49.819 12908 12935 E RomConfig: java.io.FileNotFoundException: /storage/emulated/0/MultiBoot/primary/config.json: open failed: ENOENT (No such file or directory)

**Comment by TugaPowerROM** [comment] 2016-01-08 22:26
Think the json its not related to this error.

**Comment by Caio99BR** [comment] 2016-01-08 22:41
For me is giving error 16.
[patch-file.txt](https://github.com/chenxiaolong/DualBootPatcher/files/83362/patch-file.txt)
Try to delete old patch file and try again.

**Comment by TugaPowerROM** [comment] 2016-01-08 23:25
Already did that prior to get patch-file , that way its not too cluttered.

**Comment by Caio99BR** [comment] 2016-01-08 23:59
D PatcherService: Input file descriptor is: 45
D PatcherService: Output file descriptor is: 44

My log
D PatcherService: Input file descriptor is: 59
D PatcherService: Output file descriptor is: 62
W libmbp  : minizip: Failed to copy raw data: META-INF/com/google/android/update-binary.orig

**Comment by chenxiaolong** [comment] 2016-01-09 04:00
I was able to reproduce the bug on the Windows build. Taking a look now.

![image](https://cloud.githubusercontent.com/assets/646253/12214280/87786600-b65b-11e5-9c1d-e2089b579dfd.png)

**Comment by chenxiaolong** [comment] 2016-01-09 05:10
The Windows issue is fixed by commit c233561fa362b97d0847feebab07ec13af0cb9b1 (snapshot version `8.0.0.r2094.gc233561`).

**Comment by chenxiaolong** [comment] 2016-01-09 05:18
I'm also able to reproduce the Android bug. Looking into it.

The strange thing is that nothing related to the error is being logged. All the output @TugaPowerROM and @Caio99BR mentioned before are normal.

**Comment by TugaPowerROM** [comment] 2016-01-09 09:08
@chenxiaolong could be related to busybox missing since cm13 removed ? But think it should not be the case.

**Comment by Caio99BR** [comment] 2016-01-09 13:02
No this happen in CM11.
01-09 10:53:48.661  8221  8760 W libmbp  : minizip: Failed to copy raw data: META-INF/com/google/android/update-binary.orig

But this happen in old versions.
Only small packages is patched.

**Comment by TugaPowerROM** [comment] 2016-01-09 13:07
lets hope @chenxiaolong can figure this out...

**Comment by Caio99BR** [comment] 2016-01-09 13:20
I have think this is related to issue #26 but after fixes of today, same error happen.
Maybe a logcat can produce error message (i not will make this because my CM is spammed by Adreno warning)

**Comment by TugaPowerROM** [comment] 2016-01-09 13:25
Will see in logcat if more accurate info its given. Latter will do this.

**Comment by Caio99BR** [comment] 2016-01-09 14:20
The error happen since the r2058 with new file choose.
I tried with no patched file and status 16, but when i try with a patched file(in release when support my device), surprise this works!!(latest snapshot)

**Comment by moishap** [comment] 2016-01-09 19:24
Doesn't look like it is specific zip file related.

**Comment by chenxiaolong** [comment] 2016-01-09 19:52
I found the root cause of the issue: the minizip library is opening the input file twice. Before I switched to using the Storage Access Framework (in 8.0.0.r2058), the app would do some horrible hacks to get the real file path and minizip would end up calling this twice:

```C
int fd = open("/sdcard/blah.zip", O_RDONLY);
```

That was hiding the issue before since minizip had two file descriptors and could access two different parts of the input file without trouble.

Now that Android's SAF is used, I can get a single file descriptor from the framework. minizip still opens the files twice, but the same file descriptor is used both times. Whenever one instance calls `lseek()`, both to affected, leading the reading of corrupted data.

Now to figure out why minizip is trying to open the file twice...

**Comment by chenxiaolong** [comment] 2016-01-09 19:54
@TugaPowerROM Could you verify that your original issue with the win32 builds is now fixed?

**Comment by chenxiaolong** [comment] 2016-01-09 20:01
The bug stems from a performance optimization in minizip: https://github.com/chenxiaolong/minizip/blob/master/unzip.c#L524

It should be rather easy to fix.

**Comment by Caio99BR** [comment] 2016-01-09 20:03
https://github.com/chenxiaolong/minizip/commit/b9be238542bb6615681d768cdff0c25e30e030bd

**Comment by Caio99BR** [comment] 2016-01-09 20:04
So this only works in small packages due to easy and fast file acess, right?

**Comment by TugaPowerROM** [comment] 2016-01-09 22:34
@chenxiaolong Win32 in lattest build its working good, now its just missing the fix in android app :)

**Comment by TugaPowerROM** [comment] 2016-01-09 22:49
Over android here its all logcat of app
[8.0.0.r2096.g723d4f5-SNAPSHOT.txt](https://github.com/chenxiaolong/DualBootPatcher/files/83873/8.0.0.r2096.g723d4f5-SNAPSHOT.txt)

**Comment by chenxiaolong** [comment] 2016-01-09 22:50
@TugaPowerROM Great, thanks for testing!

The Android issues should now be fixed in `8.0.0.r2101.gf6c3ae8`. I've also fixed several other corruption/incorrectness bugs:

* chenxiaolong/minizip@1a7eba8d4d1d5bf99d1212daecf0e988a8d424c3 and chenxiaolong/minizip@da5122f4340102db1ded485ceea9acf5d14c3c10: Prevent fds from being opened twice on Android
* e5abed26c3071c69e73f3d289f7aa65bd3572884 Improve error checking and logging to make issues like this easier to debug
* 90e0f4bbe8da8cd8eb18b194998550a5ad303aee Fixes invalid file modification times inside zip if paths have non-ASCII unicode characters Windows
* 69ee990d5635ef318e7f2fb9230a261a0340f064 Fixes invalid file modification times inside zip that always occurs on Android

**Comment by TugaPowerROM** [comment] 2016-01-09 22:52
Cool, wainting to test ...

**Comment by TugaPowerROM** [comment] 2016-01-09 23:00
Confirm, r2101 its great. Sucess...

**Comment by chenxiaolong** [comment] 2016-01-09 23:01
Woot! :D

**Closed by chenxiaolong** 2016-01-09 23:01 UTC
Labels: component/gui/android, kind/bug
